# Generated by Django 6.1.1 on 2026-09-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleitem_cost_total_saleitem_unit_cost_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='saleitem',
            name='sale_item_cost_total_gte_0',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='cost_total',
        ),
    ]
