# Generated by Django 6.1.1 on 2026-09-05 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_cancellations', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancellation', to='purchases.purchase')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancellation', to='sales.sale')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('purchase__isnull', True), ('sale__isnull', False)), models.Q(('purchase__isnull', False), ('sale__isnull', True)), _connector='OR'), name='exactly_one_of_sale_or_purchase'), models.UniqueConstraint(condition=models.Q(('sale__isnull', False)), fields=('sale',), name='unique_sale_cancellation'), models.UniqueConstraint(condition=models.Q(('purchase__isnull', False)), fields=('purchase',), name='unique_purchase_cancellation')],
            },
        ),
    ]
